# Generated by Django 4.2.1 on 2023-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rental", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_company", models.CharField(max_length=50, verbose_name="")),
                ("car_model", models.CharField(max_length=50, verbose_name="")),
                ("rent_start_time", models.TimeField(verbose_name="")),
                ("rent_end_time", models.TimeField(verbose_name="")),
                ("rent_price", models.IntegerField(verbose_name="")),
            ],
        ),
    ]
