# Generated by Django 4.2.1 on 2023-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rental", "0002_orders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car_renter",
            name="id",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="id",
        ),
        migrations.AddField(
            model_name="car_renter",
            name="car_renter_id",
            field=models.IntegerField(
                default=0, primary_key=True, serialize=False, verbose_name=""
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="order_id",
            field=models.IntegerField(
                default=0, primary_key=True, serialize=False, verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
