# Generated by Django 4.2.1 on 2023-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rental", "0003_remove_car_renter_id_remove_orders_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car_renter",
            name="car_renter_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=""),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=""),
        ),
    ]
