# Generated by Django 4.2.1 on 2023-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="car_model",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="date_of_registration",
            field=models.CharField(max_length=50),
        ),
    ]
