# Generated by Django 4.2.1 on 2023-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_car_price_alter_car_car_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_registration_state",
            field=models.CharField(default=0, max_length=50, verbose_name=""),
            preserve_default=False,
        ),
    ]
