# Generated by Django 4.2.1 on 2023-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_car_registration_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="id",
        ),
        migrations.AddField(
            model_name="car",
            name="car_id",
            field=models.IntegerField(
                default=0, primary_key=True, serialize=False, verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
