# Generated by Django 4.2.1 on 2023-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_car_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_fueltype",
            field=models.CharField(default=0, max_length=50, verbose_name=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="date_of_registration",
            field=models.DateField(verbose_name=""),
        ),
    ]
