# Generated by Django 4.2.1 on 2023-05-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car_leaser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_owner_name", models.CharField(max_length=50, verbose_name="")),
                ("car_owner_email", models.EmailField(max_length=254, verbose_name="")),
                ("car_owner_mobile_number", models.IntegerField(verbose_name="")),
                (
                    "car_owner_car_company",
                    models.CharField(max_length=50, verbose_name=""),
                ),
                (
                    "car_owner_car_model",
                    models.CharField(max_length=50, verbose_name=""),
                ),
            ],
        ),
    ]
