# Generated by Django 4.2.1 on 2023-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_lease", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_leaser",
            name="car_owner_car_price",
            field=models.IntegerField(default=0, verbose_name=""),
            preserve_default=False,
        ),
    ]
