# Generated by Django 4.2.1 on 2023-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_lease", "0002_car_leaser_car_owner_car_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car_leaser",
            name="id",
        ),
        migrations.AddField(
            model_name="car_leaser",
            name="car_owner_id",
            field=models.IntegerField(
                default=0, primary_key=True, serialize=False, verbose_name=""
            ),
            preserve_default=False,
        ),
    ]
