# Generated by Django 4.2.1 on 2023-05-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_lease", "0004_alter_car_leaser_car_owner_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_leaser",
            name="car_owner_password",
            field=models.CharField(default=0, max_length=50, verbose_name=""),
            preserve_default=False,
        ),
    ]
